//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mHosts.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mHosts.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;zh&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot;
        ///          content=&quot;width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge,ie=11,ie=10,ie=9&quot;&gt;
        ///    &lt;title&gt;关于&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: &apos;Microsoft YaHei&apos;,Arial, Helvetica, sans-serif;padding: 20px&quot;&gt;
        ///&lt;h1&gt;{0} v{1}&lt;/h1&gt;
        ///&lt;h4&gt;免费好用的跨平台Hosts管理工具&lt;/h4&gt;
        ///&lt;table style=&quot;width:100%&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;text- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;zh&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot;
        ///	      content=&quot;width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0&quot;&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge,ie=11,ie=10,ie=9&quot;&gt;
        ///	&lt;title&gt;关于&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: &apos;Microsoft YaHei&apos;,Arial, Helvetica, sans-serif;padding: 20px&quot;&gt;
        ///&lt;h1&gt;{0} v{1}&lt;/h1&gt;
        ///&lt;h4&gt;免费好用的跨平台Hosts管理工具&lt;/h4&gt;
        ///&lt;table style=&quot;width:100%&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&apos;text-align: right;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutHtml {
            get {
                return ResourceManager.GetString("AboutHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aliyun {
            get {
                object obj = ResourceManager.GetObject("aliyun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chrome {
            get {
                object obj = ResourceManager.GetObject("chrome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darwin {
            get {
                object obj = ResourceManager.GetObject("darwin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeFang.mHost.Net.Debug.
        /// </summary>
        internal static string DebugSingleInstanceKey {
            get {
                return ResourceManager.GetString("DebugSingleInstanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edge {
            get {
                object obj = ResourceManager.GetObject("edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap firefox {
            get {
                object obj = ResourceManager.GetObject("firefox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap java {
            get {
                object obj = ResourceManager.GetObject("java", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linux {
            get {
                object obj = ResourceManager.GetObject("linux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mysql {
            get {
                object obj = ResourceManager.GetObject("mysql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap postgresql {
            get {
                object obj = ResourceManager.GetObject("postgresql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qq {
            get {
                object obj = ResourceManager.GetObject("qq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeFang.mHost.Net.Release.
        /// </summary>
        internal static string SingleInstanceKey {
            get {
                return ResourceManager.GetString("SingleInstanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于 {0} - v{1}.
        /// </summary>
        internal static string StrAboutSoftware {
            get {
                return ResourceManager.GetString("StrAboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新工具(&amp;A).
        /// </summary>
        internal static string StrAddNewTool {
            get {
                return ResourceManager.GetString("StrAddNewTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公共.
        /// </summary>
        internal static string StrCommon {
            get {
                return ResourceManager.GetString("StrCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统当前.
        /// </summary>
        internal static string StrCurrentSystem {
            get {
                return ResourceManager.GetString("StrCurrentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string StrCustom {
            get {
                return ResourceManager.GetString("StrCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string StrDelete {
            get {
                return ResourceManager.GetString("StrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双击.
        /// </summary>
        internal static string StrDoubleClick {
            get {
                return ResourceManager.GetString("StrDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string StrEdit {
            get {
                return ResourceManager.GetString("StrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string StrExit {
            get {
                return ResourceManager.GetString("StrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        internal static string StrExport {
            get {
                return ResourceManager.GetString("StrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已保存到{0}.
        /// </summary>
        internal static string StrExportFileAt {
            get {
                return ResourceManager.GetString("StrExportFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出文件出错.
        /// </summary>
        internal static string StrExportFileError {
            get {
                return ResourceManager.GetString("StrExportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件导出成功.
        /// </summary>
        internal static string StrExportSuccess {
            get {
                return ResourceManager.GetString("StrExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前共有{0}个规则.
        /// </summary>
        internal static string StrHostsCount {
            get {
                return ResourceManager.GetString("StrHostsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts名称不能为空.
        /// </summary>
        internal static string StrHostsNameCanNotEmpty {
            get {
                return ResourceManager.GetString("StrHostsNameCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts名称“{0}”已存在.
        /// </summary>
        internal static string StrHostsNameExist {
            get {
                return ResourceManager.GetString("StrHostsNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线Hosts地址“{0}”已存在.
        /// </summary>
        internal static string StrHostsUrlExist {
            get {
                return ResourceManager.GetString("StrHostsUrlExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入文件出错.
        /// </summary>
        internal static string StrImportFileError {
            get {
                return ResourceManager.GetString("StrImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入成功.
        /// </summary>
        internal static string StrImportSuccess {
            get {
                return ResourceManager.GetString("StrImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建Hosts.
        /// </summary>
        internal static string StrNewHosts {
            get {
                return ResourceManager.GetString("StrNewHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查导入的文件是否是mHosts导出的文件.
        /// </summary>
        internal static string StrPleaseCheckTheFileIsMHostExported {
            get {
                return ResourceManager.GetString("StrPleaseCheckTheFileIsMHostExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入在线Hosts地址.
        /// </summary>
        internal static string StrPleaseInputOnlineHostUrl {
            get {
                return ResourceManager.GetString("StrPleaseInputOnlineHostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新DNS缓存.
        /// </summary>
        internal static string StrRefreshDNS {
            get {
                return ResourceManager.GetString("StrRefreshDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        internal static string StrSaveFailed {
            get {
                return ResourceManager.GetString("StrSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务已启动.
        /// </summary>
        internal static string StrServiceIsBound {
            get {
                return ResourceManager.GetString("StrServiceIsBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务未启动.
        /// </summary>
        internal static string StrServiceNotBound {
            get {
                return ResourceManager.GetString("StrServiceNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置为当前.
        /// </summary>
        internal static string StrSet2Current {
            get {
                return ResourceManager.GetString("StrSet2Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏主窗口.
        /// </summary>
        internal static string StrToggleMainForm {
            get {
                return ResourceManager.GetString("StrToggleMainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wechat {
            get {
                object obj = ResourceManager.GetObject("wechat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
